# Extensive test runner to catch compilation errors.
name: build_test
on:
  push:
    branches:
      - dev_next
jobs:
  build-binaries:
    defaults:
      run:
        shell: bash
    runs-on: akashi
    container:
      image: gitea-service:80/actions/arch-action-runner-full:latest
      options: "--security-opt seccomp=unconfined --security-opt apparmor=unconfined --device /dev/fuse:rw"
      credentials:
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_ACCESS_TOKEN}}
    steps:
      - uses: http://gitea-service/actions/checkout@v4
        with:
          show-progress: false
          submodules: true
      - name: Setup rustup targets
        run: |
          rustup default stable;
          rustup target add aarch64-unknown-linux-gnu \
          aarch64-unknown-linux-musl \
          arm-unknown-linux-musleabi \
          armv7-unknown-linux-musleabi \
          riscv64gc-unknown-linux-gnu \
          x86_64-unknown-linux-gnu \
          x86_64-unknown-linux-musl;
      - name: Run tests
        run: make test
      - name: Build binaries
        run: >
          export CARGO_TERM_QUIET=true;
          make build-all BUILD_CONFIG="build.test.config.json"
