# Simple test runner that works on all branches.
name: test
on:
  push:
    branches-ignore:
      - dev_next
jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: akashi
    container:
      image: gitea-service:80/actions/arch-action-runner-full:latest
      credentials:
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_ACCESS_TOKEN}}
    steps:
      - uses: http://gitea-service/actions/checkout@v4
        with:
          show-progress: false
          submodules: true
      - name: Setup rustup targets
        run: |
          rustup default stable
      - name: Run tests
        run: make test
