[package]
name = "tsdb"
description = "Experimental primitive timeseries database backed by LMDB."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[build-dependencies]
bindgen = { version = "0.72" }
cc = { version = "1" }
